chore(misc): dummp

diff --git a/base/scripts/.scripts/boxes b/base/scripts/.scripts/boxes
--- a/base/scripts/.scripts/boxes
+++ b/base/scripts/.scripts/boxes
@@ -1,5 +1,20 @@
 #!/bin/env bash
 
-box=$(echo -en "bytelearn1234/cdn-invalidation:dev\nbytelearn/hcsolveer:preprod\npython:3.11\narchlinux\nalpine\ndebian\nubuntu:20.04\nfedora\nnode:14.20.0-bullseye-slim\nmcr.microsoft.com/playwright\nmcr.microsoft.com/playwright:v1.25.0-focal" | fzf -i +m --height 10% --reverse )
-echo $box
-docker run -w /workdir -p 8000:8000 -it --rm -v `pwd`:/workdir $box bash
+while getopts "n:" opt; do
+  case $opt in
+    n)
+      box=$OPTARG
+      ;;
+    \?)
+      echo "Invalid option: -$OPTARG" >&2
+      exit 1
+      ;;
+  esac
+done
+
+if [ -z "$box" ]; then
+  box=$(echo -en "python:3.11\narchlinux\nalpine\ndebian\nubuntu:20.04\nfedora" | fzf -i +m --height 10% --reverse )
+fi
+
+echo "$box"
+docker run -w /workdir -p 8000:8000 -it --rm -v "$(pwd)":/workdir "$box" bash
